- name: Install AD-Domain-Services
  win_feature:
    name: AD-Domain-Services
    state: present
  become: yes
  register: ad_domain_results

- name: Reboot windows host
  win_reboot:
  become: yes
  when: ad_domain_results.rc == 0

- name: Ensure the named domain is reachable from the target host; if not, create the domain in a new forest residing on the target host
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"
  become: yes
  tags:
    - domain_check

- name: Prints out the domain list available
  win_command: nltest /dclist:{{ ad_domain_name }}
  become: yes
  tags:
    - print_domain_list
  register: domain_list_output

- debug:
    var: domain_list_output
  tags:
    - print_domain_list