- name: Install AD-Domain-Services
  win_feature:
    name: AD-Domain-Services
    state: present
    
- name: Ensure the named domain is reachable from the target host; if not, create the domain in a new forest residing on the target host
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"

- name: Reboot windows host
  win_reboot:

- name: Prints out the domain list available
  win_shell: nltest /dclist:"{{ ad_domain_name }}"